package com.gitvault.app.ui.screens

import io.noties.prism4j.Prism4j
import io.noties.prism4j.annotations.PrismBundle

/**
 * Generated by kapt @PrismBundle annotation processor.
 * Locates Prism4j grammar definitions for syntax highlighting.
 */
@PrismBundle(
    include = [
        "markup", "css", "clike", "javascript", "java", "kotlin",
        "python", "json", "yaml", "bash", "sql", "xml", "markdown", "git",
        "go", "rust", "swift", "typescript", "c", "cpp", "makefile", "docker",
        "nginx", "ini", "toml", "properties", "graphql", "protobuf"
    ]
)
class GrammarLocator : io.noties.prism4j.GrammarLocator {
    override fun grammar(prism4j: Prism4j, language: String) = null
}
